blogs/urls.py
from django.urls import path
from blogs import views
from .views import PostCreateView, CategoryListView, PostDetailView, FeaturedListView, SearchResultsView

app_name='blogs'

urlpatterns = [
    path('', views.home_page),
    path('post/new', PostCreateView.as_view(), name="blog-new"),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post'),
    path('featured/', views.FeaturedListView.as_view(), name='featured'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('category/<int:pk>', views.CategoryListView.as_view(), name='category'),
    path('search/', views.SearchResultsView.as_view(), name='search'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

#Django busca urls de arriba hacia abajo hasta que coincida con alguno de ellos
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')) #se dirige a los urls de blogs
]

blogs/models.py
from django.db import models
from django.conf import settings
from users.models import User
from django.urls import reverse
from django.utils import timezone

# Create your models here.

#Clase post la cual tiene su titulo, slug, overview, fecha de creado, contenido y autor.
class Post(models.Model):
    title=models.CharField(max_length=255)
    date_created=models.DateTimeField(auto_now_add=True)
    content=models.TextField()
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    categories=models.ManyToManyField('Category')   #un post puede tener varias categorias y una categoria puede tener muchos post=ManyToManyField
    featured=models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=timezone.now)

    #funcion la cual entrega el slug de cada post
 
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
         return reverse("blogs:post", kwargs={"pk": self.pk})

    #Clase la cual ordena los post por orden de mas reciente a mas antiguo
    class Meta:
        ordering=["-date_created"]
    



class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("blogs:category", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

users/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):


    def __str__(self):
        return f'{self.last_name}, {self.first_name}'
    

blogs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.views.generic import DetailView,CreateView
from django.utils import timezone
from django.db.models import Q
from blogs.models import Post, Category #vamos importando nuestros modelos

# Create your views here.

def home_page(request):
    posts = Post.objects.filter(
        pub_date__lte=timezone.now()
    )
    categories = Category.objects.all()
    featured = Post.objects.filter(featured=True).filter(
        pub_date__lte=timezone.now()
    )[:3]

    context = {
        'post_list': posts,
        'categories': categories,
        'featured': featured
    }

    return render(request, 'blogs/home_page.html', context=context)



class PostDetailView(generic.DetailView):
    model = Post
    queryset = Post.objects.filter(
        pub_date__lte=timezone.now()
    )
    #metodo para que tome en cuenta las categorias
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context



class PostCreateView(CreateView):
    model = Post
    queryset = Post.objects.filter(
        pub_date__lte=timezone.now()
    )
    fields=['title', 'content', 'categories']

    def get_queryset(self):
        query = Post.objects.filter(featured=True).filter(
            pub_date__lte=timezone.now()
        )
        return query

    def form_valid(self, form):
        form.instance.author=self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class FeaturedListView(generic.ListView):
    model = Post
    template_name = 'blogs/results.html'

    def get_queryset(self):
        query = Post.objects.filter(featured=True).filter(
            pub_date__lte=timezone.now()
        )
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class CategoryListView(generic.ListView):
    model = Post
    template_name = 'blogs/results.html'

    def get_queryset(self):
        query = self.request.path.replace('/category/', '')
        print(query)
        post_list = Post.objects.filter(categories__id=query).filter(
            pub_date__lte=timezone.now()
        )
        return post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

class SearchResultsView(generic.ListView):
    model = Post
    template_name = 'blogs/results.html'

    def get_queryset(self):
        query = self.request.GET.get('search')  #conseguimos el input que el usuario ingreso en el search   
        post_list = Post.objects.filter(
            Q(title__icontains=query)|Q(categories__title__icontains=query) #filtramos post cuyo titulo contenga el query que paso el usuario
        ).filter(
            pub_date__lte=timezone.now()
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

users/views.py
from django.shortcuts import render

# Create your views here.

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Blog</title>
    <link rel="icon" type="image/x-icon" href="/media/logo_adobe_express.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

          
</head>
<body>
        

{% include "navbar.html" %}
{% block content %} {% endblock content %}



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>


</body>
</html>

blogs/templates/blogs/featured.html
<div id="carouselIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for f in featured %}
            <div class="carousel-item {% if f == featured|first %}active{% endif %}">
                <div class="px-5 p-md-5 mb-4 rounded text-bg-success bg-dark" style="height: 300px">
                    <div class="col-md-10 px-5 mx-5">
                        <h1 class="display-4 fw-bold px-5">{{ f.title }}</h1>
                        <p class="lead my-3 px-5">{{ f.overview }}</p>
                        <p class="lead mb-0 px-5"><a href="{{f.get_absolute_url}}" class="text-white fw-bold">Continuar
                            leyendo...</a></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

blogs/templates/blogs/home_page.html
{% extends 'base.html' %}

{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
    
            <div class="col-md-12">
                {% include "blogs/featured.html" %}
            </div>
    
        </div>

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Más Artículos
                </h3>
                {% for post in post_list %}
                    <article class="blog-post">
                        <h2 class="blog-post-title mb-1">
                            <a href="{% url 'blogs:post' post.id %}" style="text-decoration: none"   
                               class="text-black">
                                {{ post.title }}
                            </a>
                        </h2>
                        <p class="blog-post-meta">{{ post.date_created.date }}. {{post.author}}</p>

                        <hr>
                        <p>{{ post.overview }}</p>
                    </article>
                {% endfor %}

            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic">Sobre</h4>
                        <p class="mb-0">En este blog se encontrará material acerca de las asignaturas de la carrera Ingenieria Civil en Computación e Informática.</p>
                    </div>
            
                    <div class="p-4">
                        <h4 class="fst-italic">Más Cosas?</h4>
                    </div>
                </div>
            </div>
        </div>

        

    </main>
</div>
{% endblock content %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block content %} 

<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-12">

                <div class="row">
                    <div class="d-flex justify-content-between">
                        <h1>{{ post.title }}</h1>
                        <div class="align-self-end">Publicado: {{ post.date_created.date }}</div>
                    </div>
                </div>
                <hr class="d-none d-md-block my-2 mb-3 mt-2">
                

                <p>{{ post.content | markdown | safe }}</p>

            </div>
        </div>

    </main>
</div>

{% endblock content %}

blogs/templates/blogs/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %} 
    <div class="content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Crear un post</legend>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Publicar</button>
            </div>
        </form>
        
    </div>

{% endblock content %} 

blogs/templates/blogs/results.html
{% extends 'base.html' %}


{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Destacados
                </h3>
                {% for post in post_list %}
                <div class="card mb-3">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="card-img-top" alt="thumbnail">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.overview }}</p>
                        <p class="card-text"><small class="text-muted">Last updated {{ post.pub_date.date }}</small></p>
                    </div>
                </div>
                {% endfor %}

            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic">Posts destacados encontrados:</h4>
                        <p class="mb-0">{{post_list|length}}</p>
                    </div>
            
                </div>
            </div>
        </div>

        

    </main>
</div>
{% endblock  %} 

blogs/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">ICCI<span class="text-primary">&nbsp;Unap</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Inicio</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:featured' %}">Destacados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.icci-unap.cl/">Icci</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                       Asignaturas
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li><a class="dropdown-item"
                                   href="{% url 'blogs:category' category.id %}">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blogs:blog-new' %}">Crear Post</a>
                    </li>
                </li>
            </ul>
            
            
            <form class="d-flex" role="search" action="{% url 'blogs:search'%}" method="get">
                <input name="search" class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
            
        </div>
    </div>
</nav>